version: '3.1'

services:
  db:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - 5432:5432
