import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { trpc } from '@/libs/trpc'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const {mutate,data} = trpc.hello.useMutation();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <h2>Chat yesnow</h2>
        <button onClick={() => {
          mutate()
        }}>
          Hello
        </button>
        {
          data && <p>{data}</p>
        }
      </main>
    </>
  )
}
