import { BaseHead } from "@/features/headMeta";
import "sanitize.css";
import "@/styles/base.css";

export const metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<BaseHead />
			<body>{children}</body>
		</html>
	);
}
